version: "3.7"

services:
  php:
    hostname: php
    image: php:5.6.31-apache
      #ports:
      #- 8083:80
    #volumes:
    # - ~/.docker-volumes/acagen/php/data:/var/www/html

  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    #restart: always
    ports:
    - 8082:82

  mysql:
    hostname: mysql
    build:
      context: .
      dockerfile: configs/dockerfile-mysql
      #  image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_USER: admin
      MYSQL_PASSWORD: xsZ4n5XHIBmkHzZAZbQAgCcYQE56VG
      MYSQL_DATABASE: acahealth
    volumes:
        - ./configs/mysql-dump-acahealth.sql:/docker-entrypoint-initdb.d/dump.sql
      #volumes:
            #- ~/.docker-volumes/acagen/mysql/data:/var/lib/mysql
            #- .mysql-dump:/docker-entrypoint-initdb.d

  mysql-logging:
    hostname: mysql-logging
    build:
      context: .
      dockerfile: configs/dockerfile-mysql
      #  image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_USER: admin
      MYSQL_PASSWORD: xsZ4n5XHIBmkHzZAZbQAgCcYQE56VG
      MYSQL_DATABASE: acahealthlogging
    volumes:
        - ./configs/mysql-dump-acahealthlogging.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
        - 3307:3306
   
  acahealth:
    hostname: acahealth
    build:
      context: .
      dockerfile: configs/dockerfile-acahealth
    links:
      - php
      - mysql
      - mysql-logging
    #volumes:
      # This solution doesn't work on windows. :-(
      # you need to pass the github code via the Dockerfile
      #- ${PWD}/acagen_main_code:/var/www/foo
    ports:
     - '8080:80'
