FROM mysql:5.6

COPY configs/mysql-dump-acahealth.sql /docker-entrypoint-initdb.d/init.sql
COPY configs/mysql-dump-acahealthlogging.sql /docker-entrypoint-initdb.d/init.sql

EXPOSE 3306
#ADD mysql-dump /docker-entrypoint-initdb.d

